### ISSUE TITLE
display() barchart bokeh renderer raises codec error in Python 2.7

### ISSUE THREAD

**Issue by ptitzler** [ibm-watson-data-lab/pixiedust#431]
* PD 1.0.x
* Python 2.7 ("works(1)" on 3.5 or with matplotlib renderer)

```
d = [{'title': u'Offline First: What\ufffds in a name?', 'count': 1}] 
df = pd.DataFrame(d) 
display(df)
```

* Select bar chart + bokeh as renderer

Error: `ascii' codec can't encode character u'\ufffd' in position 19: ordinal not in range(128)`

(1) Neither renderer displays the unicode character properly.

**Comment by DTAIEB** [comment]
I think this bug is a user errror:
from https://pythonhosted.org/six/
Note On Python 2, u() doesn’t know what the encoding of the literal is. Each byte is converted directly to the unicode codepoint of the same value. Because of this, it’s only safe to use u() with strings of ASCII data.
This will work on python 2.7 and 3.5
d = [{'title': unicode('Offline First: What\ufffds in a name?'), 'count': 1}] 
df = pd.DataFrame(d) 
display(df)

Closing this issue, feel free to reopen if questions remain
