### ISSUE TITLE
As a user, I want to import pixiedust so that "display()" doesn't  clobber any other local function called "display"

### ISSUE THREAD

**Issue by gadamc** [ibm-watson-data-lab/pixiedust#455]
As a user, I want to import pixiedust so that "display()" doesn't  clobber any other local function called "display"

### Expected behavior
I think that it's bad practice in python for the `__init__.py` file to automatically import functions into the local namespace. If a user has a local function called `display()`, or if they've done something like `from my_lib import display`, then that display function will be clobbered by `import pixiedust` without knowing it has happened. It could be a very difficult bug for them to figure out.  

I think that pixiedust should be changed so that one MUST do this:

```
import pixiedust

pixiedust.display(df)
```

If the caller knows what they're doing, then they can import display into the local namespace.

```
from pixiedust import display
```

**Comment by DTAIEB** [comment]
@gadamc I partially agree, I think it's very convenient to simply use display without namespacing it with pixiedust. Users have been using that behaviour from the start and it's in line with what other Notebooks do. 
I'd like to suggest a first come first serve approach. If display is already taken at the time we first import pixiedust, then we don't override it, but if not, then it's ok to take it. Users can always override it themselves afterwards if they want to.
Also, I agree that we should be able to always call pixiedust.display. This will be fixed with this ticket.
