### ISSUE TITLE
Release 1.1.0.1 is not tagged

### ISSUE THREAD

**Issue by rolweber** [ibm-watson-data-lab/pixiedust#479]
I see a release 1.1.0.1 on PyPI, but no corresponding tag in GitHub as per [#468](https://github.com/ibm-watson-data-lab/pixiedust/issues/468#issuecomment-335715243).

https://pypi.org/project/pixiedust/1.1.0.1/

**Comment by DTAIEB** [comment]
@rolweber this is an emergency patch release with no code changes. Manifest.in needed to be updated to include a few html template files needed for the new PixieGateway component. Still, I should have created a tag (obviously not yet an automatism for me :-)). Anyway, a PR has since went in master, I don't think I can retroactively create a tag now.
